### ISSUE TITLE
Sequence details not populated for tree "clusters"

### ISSUE THREAD

**Issue by RouxCil** [PoonLab/covizu#190] opened 2020-12-02 13:55 UTC
<img width="267" alt="Screen Shot 2020-12-02 at 08 52 13" src="https://user-images.githubusercontent.com/6604824/100881437-edca1e00-347b-11eb-8028-bbdc7441277f.png">

**Comment by ArtPoon** [comment] 2020-12-07 16:08
Duplicate of #191

**Closed by ArtPoon** 2020-12-07 16:08 UTC
