### ISSUE TITLE
Null values in Country distribution table

### ISSUE THREAD

**Issue by RouxCil** [PoonLab/covizu#189] opened 2020-12-02 13:53 UTC
<img width="267" alt="Screen Shot 2020-12-02 at 08 52 13" src="https://user-images.githubusercontent.com/6604824/100881259-b52a4480-347b-11eb-9f1c-278ff1687d15.png">

**Comment by ArtPoon** [comment] 2020-12-07 16:01
Might be resolved by integrating new GISAID feed?

**Comment by ArtPoon** [comment] 2020-12-07 16:02
Also need to check whether this problem is due to missing data in country field for some records - if so, we should probably drop them?

**Comment by ArtPoon** [comment] 2020-12-16 19:35
`null` still appears with feed version.
Also `United States` is not an expected field value, have to figure out why that's there.

**Comment by ArtPoon** [comment] 2020-12-16 19:45
Ok, null values are caused by unsampled lineages.  I revised the table generating function (renamed from `table` to `tabulate`) to skip null values.

**Comment by ArtPoon** [comment] 2020-12-16 19:49
United States was appearing as a region because I had mapped the value `env` to `United States` in `countries.json`.  Fixed in `dev` branch.

**Closed by ArtPoon** 2020-12-16 19:49 UTC
