### ISSUE TITLE
Tips in timetree are being rendered outside of panel

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#512] opened 2024-02-20 15:00 UTC
<img width="260" alt="Screenshot 2024-02-20 at 9 59 43 AM" src="https://github.com/PoonLab/covizu/assets/1109328/3482441c-dec5-406b-99d0-e6b65126fb77">

**Comment by ArtPoon** [comment] 2024-02-20 15:42
Looks like this problem is at the level of generating the timetree (visualizing `timetree.nwk` below):
<img width="866" alt="Screenshot 2024-02-20 at 10 41 42 AM" src="https://github.com/PoonLab/covizu/assets/1109328/9750d42f-7896-49a3-8b8a-4d893f0922a3">

**Comment by ArtPoon** [comment] 2024-02-20 21:24
@GopiGugan I'm running some tests on Paphlagon

**Comment by ArtPoon** [comment] 2024-02-20 21:30
Using the following script to extract `by_lineage.json` file from latest provision:
```python
import covizu
from covizu.utils import gisaid_utils
from covizu.utils.progress_utils import Callback
from covizu.utils.batch_utils import *
import os

cb = Callback()

infile = "data/provision.2024-02-17T00:00:21.json.xz"
ref_file = os.path.join(covizu.__path__[0], "data/NC_045512.fa")
vcf_file = os.path.join(
    covizu.__path__[0],
    "data/ProblematicSites_SARS-CoV2/problematic_sites_sarsCov2.vcf")

loader = gisaid_utils.load_gisaid(infile, minlen=29000, mindate="2019-12-01",
                                  debug=None) #100)
batcher = gisaid_utils.batch_fasta(loader, size=2000)
aligned = gisaid_utils.extract_features(
    batcher, ref_file=ref_file, binpath="minimap2", nthread=16, minlen=29000)
filtered = gisaid_utils.filter_problematic(
    aligned, vcf_file=vcf_file, cutoff=0.001, callback=cb.callback)
by_lineage = gisaid_utils.sort_by_lineage(filtered, callback=cb.callback)

with open("iss512.json", 'w') as outfile:
    json.dump(by_lineage, outfile)
```

**Comment by ArtPoon** [comment] 2024-02-22 19:10
![Screenshot from 2024-02-22 14-01-45](https://github.com/PoonLab/covizu/assets/1109328/21a64247-edcb-42e7-bf95-c0a165173a2e)
Reproduced the tree.  Looks like this is not a backend problem.

**Comment by GopiGugan** [comment] 2024-02-22 22:15
> Reproduced the tree. Looks like this is not a backend problem.

I'll take a look at the front end

**Comment by GopiGugan** [comment] 2024-03-04 15:02
I believe the issue is that we aren't scaling the nwk tree itself. Branch lengths are being assigned with the values in the nwk file:

https://github.com/PoonLab/covizu/blob/10a40174019acf76ce417631a495dcba83da4908/server/phylo.js#L59-L71

**Comment by ArtPoon** [comment] 2024-03-05 14:37
> I believe the issue is that we aren't scaling the nwk tree itself. Branch lengths are being assigned with the values in the nwk file:

I don't think this is the problem, the branch lengths in this tree are scaled in units of time (years), which is what we want to display.  I think the problem is that we are not calculating the maximum tip to root distance in this tree correctly, which would be needed to scale to the horizontal dimension of this panel.

**Comment by ArtPoon** [comment] 2024-03-05 14:43
I suspect the problem is somewhere here:
https://github.com/PoonLab/covizu/blob/10a40174019acf76ce417631a495dcba83da4908/js/drawtree.js#L122-L138

**Comment by ArtPoon** [comment] 2024-03-05 14:45
More problems:
* The timetree axis of sampling dates is not updating with the slider for specifying the minimum date for rendering lineages!
* The box for a given lineage has incorrect horizontal coordinates relative to the timetree axis.

**Comment by GopiGugan** [comment] 2024-03-11 20:43
> I suspect the problem is somewhere here:
> 
> https://github.com/PoonLab/covizu/blob/10a40174019acf76ce417631a495dcba83da4908/js/drawtree.js#L122-L138

Yes, it looks like this was the issue. The domain was not set correctly. Working on a fix for this

**Comment by GopiGugan** [comment] 2024-03-12 05:00
> * The box for a given lineage has incorrect horizontal coordinates relative to the timetree axis.

![image](https://github.com/PoonLab/covizu/assets/35086217/8c2bd409-cb36-43e0-87de-6bae81dd4f11)

In this case the tree is being drawn correctly, however the earliest collection date that we have is in 2020-11-14. This is the earliest collection date for variants that are being **displayed**

**Closed** 2024-04-10 00:42 UTC
Labels: bug
