### ISSUE TITLE
Collection date of the sample and position not matching

### ISSUE THREAD

**Issue by animesh-workplace** [PoonLab/covizu#279] opened 2021-05-01 16:51 UTC
Take a look at the position of India/MH-NCCS-86945, according to this image it looks like the collection date of this sample is 1st or 2nd October, 2020. But the actual collection date of this sample is 2021-02-13. It looks misleading and the first sample in this lineage is India/MH-NCCS-87448 with collection date 2nd October, 2020. Might be worth looking into.

![image](https://user-images.githubusercontent.com/55780901/116789149-0a21c380-aacb-11eb-8496-153164051325.png)

**Comment by ArtPoon** [comment] 2021-05-01 16:57
Hi @animesh-workplace, thanks for the feedback.  The left terminus of the horizontal line that represents the "root variant" for this lineage is drawn at 2020-10 because some of the descendant nodes in the tree were sampled at that time.  This is a limitation of the somewhat arbitrary rooting of the consensus NJ tree reconstructed from these data.  We have looked into re-rooting these trees using a root-to-tip approach, but haven't gotten around to implementing and validating such a method yet.

**Comment by ArtPoon** [comment] 2021-05-03 15:18
Closing as duplicate of #58

**Closed by ArtPoon** 2021-05-03 15:18 UTC
